### ISSUE TITLE
Tests for VESUVIO correction algorithm

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/scripts#4]
Tests for this do not yet exist as the algorithm was changing quite a bit while being developed, now that it is complete some tests should be written for it.

**Comment by DanNixon** [comment]
@ElliotAOram I've made a start on this and it should cover a lot of cases.

May need to just look at what is covered and see if there are any more values that can be checked or any other execution modes.

**Comment by ElliotAOram** [comment]
The tests have been improved during the migrations of the Vesuvio scripts and tests from the script repository
